version: "3"
services:
        db:
                build: .
                volumes:
                        - ./data:/data
                ports:
                        - "7474:7474"
                        - "7687:7687"
                environment:
                        - NEO4J_AUTH=none
